CREATE ROLE mrs LOGIN PASSWORD 'mrs' 
  NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOREPLICATION;


CREATE DATABASE mrs
  WITH OWNER = mrs
    ENCODING = 'UTF8'
    TABLESPACE = pg_default
    LC_COLLATE = 'C'
    LC_CTYPE = 'C'
    CONNECTION LIMIT = -1
    TEMPLATE = template0;
